pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        // libadb-android and sun-security-android (watch installer)
        maven { url 'https://jitpack.io' }
    }
}
rootProject.name = "Spo2Helper"
include ':shared'
include ':mobile'
include ':wear'
