plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'org.jetbrains.kotlin.plugin.compose'
}

android {
    namespace 'com.flyfish233.spo2helper'
    compileSdk 36
    compileSdkExtension 19

    defaultConfig {
        applicationId "com.flyfish233.spo2helper"
        minSdk 34
        targetSdk 36
        versionCode 3
        versionName "3.0"
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
    buildFeatures {
        compose true
    }
}

apply from: rootProject.file('gradle/signing.gradle')

dependencies {
    implementation project(':shared')
    implementation 'androidx.core:core-ktx:1.17.0'
    implementation 'androidx.activity:activity-compose:1.12.4'
    implementation 'androidx.lifecycle:lifecycle-runtime-compose:2.9.4'
    implementation platform('androidx.compose:compose-bom:2025.12.01')
    implementation 'androidx.compose.ui:ui'
    implementation 'androidx.compose.foundation:foundation'
    implementation 'androidx.wear.compose:compose-material:1.6.2'
    implementation 'androidx.wear.compose:compose-foundation:1.6.2'
    implementation 'androidx.health:health-services-client:1.1.0-rc02'
    implementation 'com.google.guava:guava:33.4.0-android'
    testImplementation 'junit:junit:4.13.2'
}
